/**
 * Baseline API Tests
 *
 * These tests verify that API endpoints respond correctly before adding new features.
 * Generated by the Brownfield Doctor based on discovered routes.
 *
 * Usage:
 * 1. Review the discovered API routes below
 * 2. Uncomment and customize tests for endpoints that should work
 * 3. Add request bodies and assertions based on expected behavior
 * 4. Run: npx vitest run tests/api/baseline.spec.ts
 *    Or:  npx playwright test tests/api/baseline.spec.ts
 */

import { test, expect } from "@playwright/test";

// Base URL for API requests - customize as needed
const API_BASE = process.env.API_BASE_URL || "http://localhost:3000";

test.describe("Baseline API Tests - Health & Status", () => {
  test("server is running", async ({ request }) => {
    // Basic connectivity check
    const response = await request.get(`${API_BASE}/`);
    expect(response.status()).toBeLessThan(500);
  });

  test("health endpoint responds", async ({ request }) => {
    // Customize: Change to your actual health endpoint
    const response = await request.get(`${API_BASE}/api/health`);

    if (response.status() === 404) {
      console.log("No /api/health endpoint - consider adding one");
      test.skip();
    }

    expect(response.ok()).toBeTruthy();
    const body = await response.json();
    expect(body).toHaveProperty("status");
  });
});

test.describe("Baseline API Tests - Authentication", () => {
  /**
   * INSTRUCTIONS:
   * Test that auth endpoints exist and respond correctly.
   * Don't test actual login here - just that endpoints work.
   */

  test.skip("login endpoint accepts POST", async ({ request }) => {
    // Customize with your actual auth endpoint
    const response = await request.post(`${API_BASE}/api/auth/login`, {
      data: {
        email: "test@example.com",
        password: "wrongpassword", // Intentionally wrong
      },
    });

    // Should get 401 for wrong creds, not 500 or 404
    expect([400, 401, 403]).toContain(response.status());
  });

  test.skip("protected endpoints return 401 without auth", async ({ request }) => {
    // Customize: Test a protected endpoint
    const response = await request.get(`${API_BASE}/api/user/profile`);
    expect([401, 403]).toContain(response.status());
  });
});

test.describe("Baseline API Tests - CRUD Operations", () => {
  /**
   * INSTRUCTIONS:
   * Add tests for your main resource endpoints.
   * Focus on verifying they respond, not full functionality.
   */

  // Example: List endpoint
  test.skip("GET /api/items returns array", async ({ request }) => {
    const response = await request.get(`${API_BASE}/api/items`);
    expect(response.ok()).toBeTruthy();

    const body = await response.json();
    expect(Array.isArray(body) || Array.isArray(body.items)).toBeTruthy();
  });

  // Example: Single item endpoint
  test.skip("GET /api/items/:id returns 404 for non-existent", async ({ request }) => {
    const response = await request.get(`${API_BASE}/api/items/non-existent-id`);
    expect(response.status()).toBe(404);
  });
});

test.describe("Baseline API Tests - Error Handling", () => {
  test("invalid JSON returns 400, not 500", async ({ request }) => {
    // Find an endpoint that accepts POST
    const response = await request.post(`${API_BASE}/api/health`, {
      headers: { "Content-Type": "application/json" },
      data: "this is not valid json{{{",
    });

    // Should handle gracefully
    expect(response.status()).toBeLessThan(500);
  });

  test("unknown endpoints return 404", async ({ request }) => {
    const response = await request.get(`${API_BASE}/api/this-does-not-exist-12345`);
    expect(response.status()).toBe(404);
  });
});

test.describe("Baseline API Tests - Response Format", () => {
  /**
   * Verify API responses follow consistent format.
   * Customize based on your API conventions.
   */

  test.skip("error responses have consistent shape", async ({ request }) => {
    // Trigger a known error
    const response = await request.get(`${API_BASE}/api/items/invalid`);

    if (!response.ok()) {
      const body = await response.json();
      // Customize: Check your error response format
      // Example: expect(body).toHaveProperty("error");
      // Example: expect(body).toHaveProperty("message");
    }
  });
});
