/**
 * Baseline Webhook Tests
 *
 * These tests verify webhook handlers process events correctly using recorded fixtures.
 * Generated by the Brownfield Doctor based on detected external services.
 *
 * Setup:
 * 1. Record webhook payloads from your external services (Stripe, SendGrid, etc.)
 * 2. Save them in tests/fixtures/webhooks/<service>/<event_type>.json
 * 3. Customize the signature generation for each service
 *
 * Usage:
 * Run: npx playwright test tests/webhooks/baseline.spec.ts
 */

import { test, expect } from "@playwright/test";
import { readFileSync, readdirSync, existsSync } from "fs";
import { join } from "path";
import { createHmac } from "crypto";

// Configuration
const API_BASE = process.env.API_BASE_URL || "http://localhost:3000";
const FIXTURES_DIR = "tests/fixtures/webhooks";

// =============================================================================
// Fixture Loading
// =============================================================================

interface WebhookFixture {
  name: string;
  eventType: string;
  payload: unknown;
}

function loadFixtures(service: string): WebhookFixture[] {
  const serviceDir = join(FIXTURES_DIR, service);

  if (!existsSync(serviceDir)) {
    console.log(`No fixtures found for ${service} at ${serviceDir}`);
    return [];
  }

  try {
    const files = readdirSync(serviceDir).filter((f) => f.endsWith(".json"));
    return files.map((file) => ({
      name: file,
      eventType: file.replace(".json", ""),
      payload: JSON.parse(readFileSync(join(serviceDir, file), "utf-8")),
    }));
  } catch (error) {
    console.error(`Error loading fixtures for ${service}:`, error);
    return [];
  }
}

// =============================================================================
// Signature Generation (customize per service)
// =============================================================================

function generateStripeSignature(payload: unknown, secret: string): string {
  const timestamp = Math.floor(Date.now() / 1000);
  const payloadString = JSON.stringify(payload);
  const signedPayload = `${timestamp}.${payloadString}`;
  const signature = createHmac("sha256", secret)
    .update(signedPayload)
    .digest("hex");
  return `t=${timestamp},v1=${signature}`;
}

function generateSendGridSignature(payload: unknown, secret: string): string {
  // SendGrid uses different signature scheme
  // Customize based on your setup
  const payloadString = JSON.stringify(payload);
  return createHmac("sha256", secret).update(payloadString).digest("hex");
}

// Add more signature generators as needed

// =============================================================================
// Stripe Webhook Tests
// =============================================================================

test.describe("Stripe Webhook Baseline", () => {
  const fixtures = loadFixtures("stripe");
  const STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET || "whsec_test";
  const STRIPE_ENDPOINT = "/api/webhooks/stripe";

  if (fixtures.length === 0) {
    test.skip("no fixtures - add recordings to tests/fixtures/webhooks/stripe/", () => {});
  }

  for (const fixture of fixtures) {
    test(`handles ${fixture.eventType}`, async ({ request }) => {
      const signature = generateStripeSignature(fixture.payload, STRIPE_WEBHOOK_SECRET);

      const response = await request.post(`${API_BASE}${STRIPE_ENDPOINT}`, {
        data: fixture.payload,
        headers: {
          "Content-Type": "application/json",
          "stripe-signature": signature,
        },
      });

      // Webhook should acknowledge receipt (200-299)
      // Some handlers return 200, others 202 for async processing
      expect(response.status()).toBeGreaterThanOrEqual(200);
      expect(response.status()).toBeLessThan(300);
    });
  }

  test("rejects invalid signature", async ({ request }) => {
    if (fixtures.length === 0) test.skip();

    const response = await request.post(`${API_BASE}${STRIPE_ENDPOINT}`, {
      data: fixtures[0].payload,
      headers: {
        "Content-Type": "application/json",
        "stripe-signature": "invalid_signature",
      },
    });

    // Should reject with 400 or 401
    expect([400, 401, 403]).toContain(response.status());
  });
});

// =============================================================================
// SendGrid Webhook Tests
// =============================================================================

test.describe("SendGrid Webhook Baseline", () => {
  const fixtures = loadFixtures("sendgrid");
  const SENDGRID_ENDPOINT = "/api/webhooks/sendgrid";

  if (fixtures.length === 0) {
    test.skip("no fixtures - add recordings to tests/fixtures/webhooks/sendgrid/", () => {});
  }

  for (const fixture of fixtures) {
    test(`handles ${fixture.eventType}`, async ({ request }) => {
      const response = await request.post(`${API_BASE}${SENDGRID_ENDPOINT}`, {
        data: fixture.payload,
        headers: {
          "Content-Type": "application/json",
        },
      });

      expect(response.status()).toBeGreaterThanOrEqual(200);
      expect(response.status()).toBeLessThan(300);
    });
  }
});

// =============================================================================
// Generic Webhook Tests
// =============================================================================

test.describe("Webhook Error Handling", () => {
  test("malformed JSON returns 400", async ({ request }) => {
    // Test against your primary webhook endpoint
    const response = await request.post(`${API_BASE}/api/webhooks/stripe`, {
      headers: { "Content-Type": "application/json" },
      data: "not valid json {{{",
    });

    expect(response.status()).toBe(400);
  });

  test("unknown webhook endpoint returns 404", async ({ request }) => {
    const response = await request.post(`${API_BASE}/api/webhooks/unknown-service`);
    expect(response.status()).toBe(404);
  });
});

// =============================================================================
// Add more services below
// =============================================================================

// test.describe("Twilio Webhook Baseline", () => {
//   const fixtures = loadFixtures("twilio");
//   // ...
// });

// test.describe("Auth0 Webhook Baseline", () => {
//   const fixtures = loadFixtures("auth0");
//   // ...
// });
